import { CharacterBackground, CharacterBackgroundId, Location, TradeGood, Unit, Item, EquipmentSlot, Faction, Companion, EnterpriseType, AILord } from './types';

export const BACKGROUND_OPTIONS: CharacterBackground[] = [
  { id: CharacterBackgroundId.NOMAD, name: '초원의 유목민', description: '말과 활에 능숙하며, 넓은 초원에서 태어났습니다.' },
  { id: CharacterBackgroundId.MERCHANT, name: '도시의 상인', description: '흥정과 계산에 밝으며, 약간의 자본을 가지고 시작합니다.' },
  { id: CharacterBackgroundId.POACHER, name: '숲의 밀렵꾼', description: '은신과 추적의 달인으로, 소규모 병력으로 시작합니다.' },
  { id: CharacterBackgroundId.NOBLE, name: '몰락한 귀족', description: '가문의 이름 덕에 약간의 명성을 가지고 시작합니다.' },
  { id: CharacterBackgroundId.BLACKSMITH, name: '마을의 대장장이', description: '강인한 체력과 좋은 장비를 가지고 시작합니다.' },
];

export const FACTIONS: Record<string, Faction> = {
  swadia: { id: 'swadia', name: '스와디아 왕국' },
  nords: { id: 'nords', name: '노르드 왕국' },
  vaegirs: { id: 'vaegirs', name: '베기어 왕국' },
  khergits: { id: 'khergits', name: '케르지트 칸국' },
  sarranids: { id: 'sarranids', name: '사라니드 술탄국' },
  neutral: { id: 'neutral', name: '중립' },
};

export const AI_LORDS: Record<string, AILord> = {
  'harlaus': {
    id: 'harlaus',
    name: '하를라우스 왕',
    factionId: 'swadia',
    army: { 'swadian_knight': 15, 'swadian_footman': 50 },
    currentLocationId: 'pravend',
    isDefeated: false,
    defeatedUntilDay: 0,
  },
  'ragnar': {
    id: 'ragnar',
    name: '라그나 왕',
    factionId: 'nords',
    army: { 'nord_huscarl': 20, 'nord_warrior': 40 },
    currentLocationId: 'sargoth',
    isDefeated: false,
    defeatedUntilDay: 0,
  },
  'yaroglek': {
    id: 'yaroglek',
    name: '야로글렉 왕',
    factionId: 'vaegirs',
    army: { 'vaegir_footman': 60 },
    currentLocationId: 'reyvadin',
    isDefeated: false,
    defeatedUntilDay: 0,
  },
  'sanjar': {
    id: 'sanjar',
    name: '산자르 칸',
    factionId: 'khergits',
    army: { 'khergit_tribesman': 70 },
    currentLocationId: 'tulga',
    isDefeated: false,
    defeatedUntilDay: 0,
  },
  'hakim': {
    id: 'hakim',
    name: '하킴 술탄',
    factionId: 'sarranids',
    army: { 'sarranid_footman': 65 },
    currentLocationId: 'dhirim',
    isDefeated: false,
    defeatedUntilDay: 0,
  }
};


export const COMPANIONS: Record<string, Companion> = {
  borcha: {
    id: 'borcha',
    name: '보르차',
    backstory: '초원에서 길을 잃은 후, 도시의 삶에 적응하지 못하고 있습니다. 그는 다시 광활한 대지를 달릴 날을 꿈꿉니다.',
    skills: { 'looting': 15, 'scouting': 10, 'tactics': 1 },
    equipment: {
      body: 'leather_jerkin',
      weapon: 'rusty_sword',
      feet: 'iron_greaves'
    },
    cost: 400,
    status: 'unrecruited',
    locationId: 'khudan',
    hp: 100,
    isWounded: false,
  },
  marnid: {
    id: 'marnid',
    name: '마르니드',
    backstory: '그가 모시던 상단이 산적에게 습격당한 후 모든 것을 잃었습니다. 그는 재기할 기회를 찾고 있습니다.',
    skills: { 'trade': 5, 'persuasion': 2 },
    equipment: {
      body: 'leather_jerkin',
      weapon: 'arming_sword'
    },
    cost: 600,
    status: 'unrecruited',
    locationId: 'pravend',
    hp: 100,
    isWounded: false,
  },
  bunduk: {
    id: 'bunduk',
    name: '번둑',
    backstory: '오랜 군 생활에 지친 그는 이제 조용한 삶을 원하지만, 녹슨 검은 아직 피를 갈망하는 듯합니다.',
    skills: { 'trainer': 2 },
    equipment: {
      body: 'mail_hauberk',
      weapon: 'arming_sword',
      head: 'great_helm'
    },
    cost: 800,
    status: 'unrecruited',
    locationId: 'sargoth',
    hp: 100,
    isWounded: false,
  },
  ymira: {
    id: 'ymira',
    name: '이미라',
    backstory: '전쟁으로 가족을 잃은 그녀는, 더 이상 다른 이들이 같은 고통을 겪지 않도록 돕겠다 맹세했습니다.',
    skills: { 'wound_treatment': 3, 'surgery': 1, 'trade': 1 },
     equipment: {
      body: 'leather_jerkin',
      weapon: 'rusty_sword',
    },
    cost: 1200,
    status: 'unrecruited',
    locationId: 'reyvadin',
    hp: 100,
    isWounded: false,
  }
};

export const UNITS: Record<string, Unit> = {
  recruit: {
    id: 'recruit',
    name: '신병',
    description: '가장 기본적인 병사입니다. 잠재력은 무한합니다.',
    recruitCost: 10,
    attack: 5,
    defense: 5,
  },
  skilled_recruit: {
    id: 'skilled_recruit',
    name: '숙련된 신병',
    description: '특별한 훈련을 받은 신병입니다. 동료 번둑이 있어야만 훈련시킬 수 있습니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 50,
    xpToUpgrade: 150,
    attack: 8,
    defense: 8,
    upgradeRequiresCompanion: ['bunduk'],
  },
  // --- Swadian Line ---
  swadian_footman: {
    id: 'swadian_footman',
    name: '스와디아 보병',
    description: '검과 방패로 무장한, 신뢰할 수 있는 보병입니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 20,
    xpToUpgrade: 100,
    attack: 10,
    defense: 12,
  },
  swadian_man_at_arms: {
    id: 'swadian_man_at_arms',
    name: '스와디아 무장병',
    description: '더 나은 무기와 갑옷을 갖춘 공격적인 보병입니다.',
    upgradeFrom: 'swadian_footman',
    upgradeCost: 50,
    xpToUpgrade: 250,
    attack: 18,
    defense: 15,
  },
  swadian_sergeant: {
    id: 'swadian_sergeant',
    name: '스와디아 하사관',
    description: '두꺼운 갑옷과 큰 방패로 무장한 방어적인 보병입니다.',
    upgradeFrom: 'swadian_footman',
    upgradeCost: 45,
    xpToUpgrade: 220,
    attack: 12,
    defense: 20,
  },
  swadian_knight: {
    id: 'swadian_knight',
    name: '스와디아 기사',
    description: '두꺼운 갑옷과 강력한 랜스로 무장한 전장의 지배자입니다.',
    upgradeFrom: 'swadian_man_at_arms',
    upgradeCost: 150,
    xpToUpgrade: 600,
    attack: 25,
    defense: 25,
    upgradeRequiresItems: { 'war_horse': 1 },
  },
  // --- Nord Line ---
  nord_warrior: {
    id: 'nord_warrior',
    name: '노르드 전사',
    description: '도끼를 휘두르는 용맹한 북부의 전사입니다. 보병전에 매우 강력합니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 30,
    xpToUpgrade: 120,
    attack: 14,
    defense: 8,
  },
   nord_huscarl: {
    id: 'nord_huscarl',
    name: '노르드 허스칼',
    description: '양손 도끼와 투척 도끼로 무장한 노르드의 정예 보병입니다.',
    upgradeFrom: 'nord_warrior',
    upgradeCost: 120,
    xpToUpgrade: 600,
    attack: 22,
    defense: 18,
    upgradeRequiresLocation: ['sargoth'],
  },
  // --- Other Factions ---
  vaegir_footman: {
    id: 'vaegir_footman',
    name: '베기어 보병',
    description: '도끼와 투박한 방패로 무장한, 추운 북부에서 온 강인한 병사입니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 25,
    xpToUpgrade: 110,
    attack: 11,
    defense: 10,
  },
  khergit_tribesman: {
    id: 'khergit_tribesman',
    name: '케르지트 부족민',
    description: '빠른 발과 날카로운 칼을 가진 초원의 전사입니다. 경기병으로 성장할 잠재력이 있습니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 20,
    xpToUpgrade: 90,
    attack: 9,
    defense: 7,
  },
  sarranid_footman: {
    id: 'sarranid_footman',
    name: '사라니드 보병',
    description: '사막의 열기 속에서 단련된 병사입니다. 창과 방패를 능숙하게 다룹니다.',
    upgradeFrom: 'recruit',
    upgradeCost: 25,
    xpToUpgrade: 100,
    attack: 10,
    defense: 11,
  },
};

export const TRADE_GOODS: Record<string, TradeGood> = {
  salt: { id: 'salt', name: '소금', basePrice: 50 },
  tools: { id: 'tools', name: '도구', basePrice: 120 },
  pottery: { id: 'pottery', name: '도자기', basePrice: 80 },
  wine: { id: 'wine', name: '포도주', basePrice: 100 },
  velvet: { id: 'velvet', name: '벨벳', basePrice: 300 },
  furs: { id: 'furs', name: '모피', basePrice: 250 },
  ale: { id: 'ale', name: '에일', basePrice: 40 },
};

export const ITEMS: Record<string, Item> = {
  tattered_rags: { id: 'tattered_rags', name: '낡은 누더기', description: '없는 것보다는 낫습니다.', slot: EquipmentSlot.BODY, price: 5, effects: { armor: 1 } },
  rusty_sword: { id: 'rusty_sword', name: '녹슨 검', description: '날이 무뎌 잘 베이지도 않습니다.', slot: EquipmentSlot.WEAPON, price: 20, effects: { attack: 2 } },
  leather_cap: { id: 'leather_cap', name: '가죽 모자', description: '약한 보호를 제공합니다.', slot: EquipmentSlot.HEAD, price: 30, effects: { armor: 2 } },
  leather_jerkin: { id: 'leather_jerkin', name: '가죽 조끼', description: '가볍고 질긴 조끼입니다.', slot: EquipmentSlot.BODY, price: 80, effects: { armor: 5 } },
  iron_greaves: { id: 'iron_greaves', name: '철 정강이받이', description: '다리를 보호합니다.', slot: EquipmentSlot.FEET, price: 60, effects: { armor: 3 } },
  arming_sword: { id: 'arming_sword', name: '아밍 소드', description: '병사들이 널리 사용하는 균형 잡힌 검입니다.', slot: EquipmentSlot.WEAPON, price: 150, effects: { attack: 5 } },
  great_helm: { id: 'great_helm', name: '그레이트 헬름', description: '머리 전체를 감싸는 투구입니다. 시야가 좁아지는 단점이 있습니다.', slot: EquipmentSlot.HEAD, price: 200, effects: { armor: 8 } },
  mail_hauberk: { id: 'mail_hauberk', name: '체인메일', description: '수많은 강철 고리로 엮어 만든 갑옷입니다.', slot: EquipmentSlot.BODY, price: 400, effects: { armor: 12 } },
  swaybacked_horse: { id: 'swaybacked_horse', name: '등이 휜 말', description: '짐을 나르는 데는 쓸모가 있지만, 전투용으로는 부적합합니다.', slot: EquipmentSlot.HORSE, price: 250, effects: { armor: 2, attack: 1 } },
  war_horse: { id: 'war_horse', name: '군마', description: '전투를 위해 훈련된 강력한 말입니다. 돌격에 큰 힘이 됩니다.', slot: EquipmentSlot.HORSE, price: 2000, effects: { armor: 5, attack: 2 } },
};

// Items available for purchase in any armorer shop
export const ARMORER_STOCK: string[] = [
  'rusty_sword',
  'leather_cap',
  'leather_jerkin',
  'iron_greaves',
  'arming_sword',
  'great_helm',
  'mail_hauberk',
  'swaybacked_horse',
  'war_horse',
];

export const ENTERPRISE_TYPES: Record<string, EnterpriseType> = {
  brewery: { id: 'brewery', name: '양조장', cost: 2500, baseWeeklyProfit: 150, outputGoodId: 'ale' },
  winery: { id: 'winery', name: '와인 양조장', cost: 3500, baseWeeklyProfit: 250, outputGoodId: 'wine' },
  ironworks: { id: 'ironworks', name: '제철소', cost: 6000, baseWeeklyProfit: 400, outputGoodId: 'tools' },
  velvet_dyery: { id: 'velvet_dyery', name: '벨벳 염색소', cost: 10000, baseWeeklyProfit: 600, outputGoodId: 'velvet'},
  fur_trader: { id: 'fur_trader', name: '모피상', cost: 8000, baseWeeklyProfit: 500, outputGoodId: 'furs'},
};


export const LOCATIONS: Record<string, Omit<Location, 'market'>> = {
  pravend: {
    id: 'pravend',
    name: '프라벤드',
    description: '스와디아 왕국의 수도입니다. 비옥한 평야에 위치해 있으며, 강력한 기사들을 모집할 수 있습니다.',
    ownerId: '하를라우스 왕',
    factionId: FACTIONS.swadia.id,
    connectedTo: ['uxkhal', 'suno'],
    recruitsAvailable: 10,
    x: 20,
    y: 40,
    production: ['velvet', 'wine', 'ale'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
  uxkhal: {
    id: 'uxkhal',
    name: '욱스칼',
    description: '프라벤드 근처의 번화한 도시입니다. 교역이 활발하며 다양한 병종을 만날 수 있습니다.',
    ownerId: '클라이스 백작',
    factionId: FACTIONS.swadia.id,
    connectedTo: ['pravend', 'suno', 'dhirim'],
    recruitsAvailable: 15,
    x: 30,
    y: 50,
    production: ['ale', 'pottery'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
  suno: {
    id: 'suno',
    name: '수노',
    description: '성과 도시가 결합된 견고한 요새입니다. 정예 보병을 훈련시키기 좋습니다.',
    ownerId: '에트로서 백작',
    factionId: FACTIONS.swadia.id,
    connectedTo: ['pravend', 'uxkhal', 'dhirim'],
    recruitsAvailable: 12,
    x: 25,
    y: 60,
    production: ['tools', 'ale'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
  dhirim: {
    id: 'dhirim',
    name: '디림',
    description: '대륙의 중심에 위치한 전략적 요충지입니다. 언제나 전운이 감도는 곳입니다.',
    ownerId: '하킴 술탄',
    factionId: FACTIONS.sarranids.id,
    connectedTo: ['uxkhal', 'suno', 'sargoth', 'reyvadin'],
    recruitsAvailable: 20,
    x: 45,
    y: 55,
    production: [], // Crossroads, no special production
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
  sargoth: {
    id: 'sargoth',
    name: '사르고스',
    description: '노르드 왕국의 수도입니다. 해안가에 위치하며, 강력한 보병들을 모집할 수 있습니다.',
    ownerId: '라그나 왕',
    factionId: FACTIONS.nords.id,
    connectedTo: ['dhirim', 'tihr'],
    recruitsAvailable: 15,
    x: 35,
    y: 20,
    production: ['pottery', 'ale'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
  tihr: {
    id: 'tihr',
    name: '티르',
    description: '사르고스 근처의 항구 도시입니다. 해적들의 위협이 잦습니다.',
    ownerId: '올라프 영주',
    factionId: FACTIONS.nords.id,
    connectedTo: ['sargoth'],
    recruitsAvailable: 25,
    x: 25,
    y: 15,
    production: ['salt', 'pottery'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
   reyvadin: {
    id: 'reyvadin',
    name: '레이바딘',
    description: '베기어 왕국의 수도입니다. 눈 덮인 땅에 있으며, 명궁들을 모집할 수 있습니다.',
    ownerId: '야로글렉 왕',
    factionId: FACTIONS.vaegirs.id,
    connectedTo: ['dhirim', 'khudan'],
    recruitsAvailable: 10,
    x: 65,
    y: 30,
    production: ['furs'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
   khudan: {
    id: 'khudan',
    name: '쿠단',
    description: '케르지트 칸국의 영토와 가깝습니다. 유목민 전사들을 만나기 쉽습니다.',
    ownerId: '아사칸 노얀',
    factionId: FACTIONS.khergits.id,
    connectedTo: ['reyvadin', 'tulga'],
    recruitsAvailable: 18,
    x: 75,
    y: 45,
    production: ['salt', 'furs'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
   tulga: {
    id: 'tulga',
    name: '툴가',
    description: '케르지트 칸국의 초원 도시입니다. 강력한 기마병들이 많습니다.',
    ownerId: '산자르 칸',
    factionId: FACTIONS.khergits.id,
    connectedTo: ['khudan'],
    recruitsAvailable: 15,
    x: 80,
    y: 65,
    production: ['salt', 'furs'],
    garrison: {},
    accumulatedTaxes: 0,
    status: 'normal',
    lootedUntilDay: 0,
  },
};